
name = "Dqb2"
uuid = "1b08a953-4be3-4667-9a23-ab763fc07c8b"
authors = ["Mohamed El-Deeb <s-mohamed.eldeeb@zewailcity.edu.eg>"]
version = "1.0.4"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
